SELECT * WHERE {
  {
    ?s1 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country9> .
    ?s1 <http://purl.org/goodrelations/includes> ?includes .
    ?s1 <http://purl.org/goodrelations/validThrough> ?validity .
  } UNION {
    ?s2 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country10> .
    ?s2 <http://purl.org/goodrelations/includes> ?includes .
    ?s2 <http://purl.org/goodrelations/validThrough> ?validity .
  }
}
